//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThuCung.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_DetailContractser
    {
        public string ID_ConSer { get; set; }
        public string ID_Ser { get; set; }
        public Nullable<int> Price { get; set; }
    }
}
