//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThuCung.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work
    {
        public System.DateTime DateWork { get; set; }
        public string Shifts { get; set; }
        public string ID_Emp { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
